src/pages/Onboarding/UserRegistration/Concept/page.tsx, src/pages/Onboarding/UserRegistration/Feature/page.tsx, src/pages/Onboarding/UserRegistration/Location/page.tsx, src/pages/Onboarding/UserRegistration/Nickname/page.tsx, src/pages/Onboarding/UserRegistration/Profile/page.tsx, src/pages/Tos/page.tsx
- resolved #11
각 페이지 조건 충족 안 했을 때 버튼 비활성화 되도록 수정
=> fix: 온보딩 버튼 오류 수정

build.sh, vercel.json
- resolved #15 
build.sh 파일 생성
vercel.json 파일 생성
=> deploy: 배포 파일 생성

src/pages/Review/page.tsx
- resolved #17 
리뷰 갯수 변경 후 빌드 테스트
=> test: 자동 빌드 테스트

package.json, src/libraries/index.tsx, yarn.lock
- resolved #32 
recoil 라이브러리 의존성 삭제
zustande 라이브러리 추가
recoil 세팅 삭제 및 recoil -> store 로 폴더 명 변경
=> feat: zustand 라이브러리 적용

src/components/Onboarding/Registration/index.tsx, src/pages/Onboarding/CompleteRegistration/page.tsx, src/pages/Onboarding/UserRegistration/Feature/const/index.ts, src/pages/Onboarding/UserRegistration/Feature/page.tsx, src/types/onboarding.ts
- resolved #37 
FeatureType, feature 상수 파일에 image 추가
온보딩 FeatureButton에 키워드 아이콘 추가
온보딩 완료 화면 포스터 패딩값 조절
https://github.com/user-attachments/assets/0ed10521-43b6-4a2b-a750-67919925657b
=> feat: onboarding republishing

src/apis/index.ts, src/components/Mypage/PreferenceAnalysis/PreferenceSettings/index.tsx, src/components/common/Age/index.tsx, src/components/common/Gender/index.tsx, src/components/common/Nickname/index.tsx, src/hooks/useNickNameCheck.ts, src/hooks/useUserInformationSubmit.ts, src/libraries/store/onboarding.ts, src/libraries/store/user.ts, src/pages/Login/Kakao/AfterOnBoarding/page.tsx, src/pages/Login/page.tsx, src/pages/Onboarding/CompleteRegistration/page.tsx, src/pages/Onboarding/UserRegistration/Concept/page.tsx, src/pages/Onboarding/UserRegistration/Feature/page.tsx, src/pages/Onboarding/UserRegistration/Location/page.tsx, src/pages/Onboarding/UserRegistration/Nickname/page.tsx, src/pages/Onboarding/UserRegistration/Price/page.tsx, src/pages/Onboarding/UserRegistration/Profile/page.tsx, src/routes/routePath.ts, src/routes/router.tsx, src/types/onboarding.ts
- resolved #52 
유저 정보 전역 상태로 관리
age 타입 number로 변경
닉네임 중복 검사 api 연동
온보딩(취향 등록) api 연동
온보딩 취향 입력 후 새로운 토큰 발급
=> feat: onboarding api

src/pages/Ticket/[id]/page.tsx
=> fix: null 값 여부에 따라 뒤로가기 로직 구분

src/hooks/mutation/usePostLike.ts
=> fix: 좋아요 쿼리 캐싱 무효화

src/hooks/mutation/usePostLike.ts, src/pages/Ticket/[id]/page.tsx
=> depoly: 좋아요 기능 수정 후 재배포

src/pages/TicketBook/[id]/page.tsx
=> fix: 빈 클라코북 오류 처리

src/hooks/mutation/usePostLike.ts, src/pages/TicketBook/[id]/page.tsx
=> depoly: 빈 클라코북 에러 처리 후 배포

src/pages/TicketBook/[id]/page.tsx
=> fix: 디자인 수정

src/pages/TicketBook/[id]/page.tsx
=> depoly: 디자인 에러 수정

src/pages/TicketBook/[id]/page.tsx
=> depoly: 재배포

src/assets/lotties/onboarding-loading.json, src/components/Browse/ShowFilter/index.tsx, src/components/ShowDetail/ShowInformation/ShowOverview/index.tsx, src/components/ShowDetail/ShowInformation/ShowPoster/index.tsx, src/components/common/CategoryTag/index.tsx, src/components/common/ShowSummaryCard/index.tsx, src/hooks/queries/index.ts, src/hooks/queries/useGetReviewAutoCompleteSearch.ts, src/hooks/utils/extractSchedule.ts, src/pages/Mypage/page.tsx, src/pages/Onboarding/CompleteRegistration/page.tsx, src/pages/ShowDetail/page.tsx, src/pages/Ticket/[id]/page.tsx, src/pages/TicketBook/[id]/page.tsx, src/pages/TicketCreate/Download/page.tsx, src/pages/TicketCreate/Info/page.tsx, src/pages/TicketCreate/Review/page.tsx, src/pages/TicketCreate/Search/page.tsx
- resolved #96 
티켓 등록 시 검색 api 추가 연동
=> feat: QA 3차

src/components/common/Search/Bar/index.tsx, src/globals.css, src/pages/Browse/page.tsx, vite.config.ts
- resolved #98 
탭 변경 시 필터 초기화
로티이미지 경로 수정
검색창 X 아이콘
=> feat: QA 4차

vite.config.ts
=> hotfix: base 경로 다시 수정

src/globals.css, src/pages/TicketBook/page.tsx, src/pages/TicketCreate/Download/page.tsx
=> Hotfix/qa #6

src/components/common/Search/Bar/index.tsx
=> fix: 검색바 고치기

src/apis/client.ts
=> fix: 로그인 리다렉 수정

src/apis/client.ts
=> fix: 에러 핸들링 수정:

src/assets/lotties/onboarding-loading.json, src/globals.css
=> feat: 요청 사항 수정

src/components/common/ShowSummaryCard/index.tsx
=> hotfix: 그라디언트 위치 수정

src/pages/TicketBook/page.tsx
=> feat: 티켓북 초기 페이지 수정

src/apis/client.ts, src/apis/index.ts, src/apis/refreshToken.ts, src/pages/Login/Kakao/AfterOnBoarding/page.tsx, src/pages/Login/Kakao/BeforeOnBoarding/page.tsx
- resolved #113 
리프레쉬 쿠키 api 연동
=> feat: 리프레쉬 쿠키 api 연동

src/apis/client.ts, src/pages/Login/Kakao/AfterOnBoarding/page.tsx, src/pages/Login/Kakao/BeforeOnBoarding/page.tsx
- resolved #(issue_num)
리프레쉬 api 연동 수정
=> feat: 리프레쉬 api 연동 수정

src/apis/client.ts
- resolved #(issue_num)
axios 헤더 수정
=> fix: axios 헤더 수정

src/pages/Mypage/UserEdit/page.tsx
- resolved #(issue_num)
프로필 이미지 api 연동 수정
=> feat: 프로필 이미지 api 연동 수정

src/apis/client.ts, src/pages/Mypage/UserEdit/page.tsx
=> deploy: 배포

src/pages/Mypage/page.tsx
- resolved #(issue_num)
마이페이지 리렌더링
=> feat: 마이페이지 리렌더링
